restuarant/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('users.urls')),
    path('',include('orders.urls'))
]

users/urls.py
from django.urls import path
from . import views

 
urlpatterns = [
    path('', views.main, name='main'),
    path('signup_user/', views.signup_user, name='signup_user'),
    path('login_view/', views.login_view, name='login_view'),
    path('admin_login/', views.admin_login, name='admin_login'),
    path('update_user/',views.update_user,name='update_user'),
    path('category_admin/',views.category_admin,name='category-admin'),
    path('category_user/',views.category_user,name="category_user"),
    path('dishes_user/<int:id>/',views.dishes_user,name="dishes_user"),
    path('edit_category/<int:id>/', views.edit_category, name='edit_category'),
    path('delete_category/<int:id>/', views.delete_category, name='delete_category'),
    path('dishes_admin/<int:id>/', views.dishes_admin, name='dishes-admin'),
    path('edit_dish/<int:id>/', views.edit_dish, name='edit_dish'),
    path('delete_dish/<int:id>/', views.delete_dish, name='delete_dish'),
    path('add_category/', views.add_category, name='add_category'),
    path('add_dish/', views.add_dish, name='add-dish'),
    path('logout_user/',views.logout_user,name='logout_user'),
    path('logout_manager/',views.logout_manager,name='logout_manager')
]

users/models.py
from django.db import models
from django.core.exceptions import ValidationError
from orders.models import Cart
 
class User(models.Model):
    first_name = models.CharField(max_length=50, blank=False, null=False)
    last_name = models.CharField(max_length=50, blank=False, null=False)
    email = models.EmailField(unique=True, blank=False, null=False)
    username = models.CharField(max_length=50, unique=True, blank=False, null=False)
    password = models.CharField(max_length=128, blank=False, null=False)
 
    def __str__(self):
        return self.username
 
    def clean(self):
        # Check that all fields are filled in
        if not self.first_name:
            raise ValidationError('First name is required')
        if not self.last_name:
            raise ValidationError('Last name is required')
        if not self.email:
            raise ValidationError('Email is required')
        if not self.username:
            raise ValidationError('Username is required')
        if not self.password:
            raise ValidationError('Password is required')





class Category(models.Model):
    name = models.CharField(max_length=200,blank=False,unique=True)
    imageUrl = models.TextField(unique=True,blank=False,null=True)

    def __str__(self):
        return self.name




class Dish(models.Model):
    name = models.CharField(max_length=200,blank=False,unique=True)
    price = models.IntegerField(blank=False,null=False)
    description = models.TextField(blank=True,null=True)
    imageUrl = models.TextField(blank=False)
    is_gluten_free = models.BooleanField(default=False)
    is_vegetarian = models.BooleanField(default=False)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)




class Item(models.Model):
    dish=models.ForeignKey(Dish,default="",on_delete=models.CASCADE)
    cart=models.ForeignKey(Cart, related_name='item' ,default="", on_delete=models.CASCADE)
    amount=models.IntegerField(default=0)

users/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Category, Dish
 
class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'username', 'password']
        widgets = {
            'password': forms.PasswordInput()
        }
        def clean_username(self):
            username = self.cleaned_data['username']
            if User.objects.filter(username=username).exists():
                raise forms.ValidationError('Username already exists')
            return username

class CategoryForm(forms.ModelForm):

    class Meta:
        model = Category
        fields = '__all__'

class DishForm(forms.ModelForm):

    class Meta:
        model = Dish
        fields = '__all__'

users/views.py
from django.shortcuts import render, redirect
from .forms import UserForm
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import make_password
from django.contrib.auth import login,authenticate,logout
from .models import Category,Dish
from django.contrib.auth.hashers import make_password
from orders.models import Cart
from .forms import CategoryForm, DishForm




def main(request):
    return render(request,'main.html')



def signup_user(request):
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.password = make_password(form.cleaned_data['password'])
            user.save()
            return redirect('login_view') 
    else:
        form = UserForm()
 
    context = {'form': form}
    return render(request, 'signup_user.html', context)




def login_view(request):
    if request.method == 'POST':
        # Get the username and password from the POST request
        username = request.POST['username']
        password = request.POST['password']

        # Authenticate the user
        user = authenticate(request, username=username, password=password)
        # If the user is authenticated, log them in and redirect to a success page
        if user is not None:
            login(request, user)
            new_cart=Cart(user=user)
            new_cart.save()
            return redirect('category_user')
        # If the user is not authenticated, show an error message
        
        else:
            error_message = "Invalid username or password"
            return render(request, 'login.html', {'error_message': error_message})
    else:
        return render(request, 'login.html')







def admin_login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None and user.is_staff:
            login(request, user)
            return redirect('category-admin')
        else:
            error_message = "Invalid login credentials or you are not authorized to access this page."
            return render(request, 'admin_login.html', {'error_message': error_message})
    else:
        return render(request, 'admin_login.html')



@login_required(login_url='login_view')
def update_user(request):
    user = request.user
    if request.method == 'POST':
        form = UserForm(request.POST, instance=user)
        if form.is_valid():
            user = form.save(commit=False)
            user.password = make_password(form.cleaned_data['password'])
            user.save()
            return redirect('login_view') # redirect to user profile page
    else:
        form = UserForm(instance=user)
 
    return render(request, 'update_user.html', {'form': form})



@login_required(login_url='admin_login')
def category_admin(request):
    categories=Category.objects.all()
    return render(request,'category_admin.html',{'categories': categories})



@login_required(login_url='login_view')
def category_user(request):
    categories=Category.objects.all()
    return render(request, 'category_user.html',{'categories': categories})


@login_required(login_url='login_view')
def dishes_user(request, id):
    category = Category.objects.get(id=id)
    dishes = Dish.objects.all()
    return render(request, 'dishes_user.html', {"category":category, "dishes":dishes})



@login_required(login_url='admin_login')
def edit_category(request,id):
    category=Category.objects.get(id=id)
    if request.method=='POST':
        category.name=request.POST['name']
        category.imageUrl=request.POST['imageUrl']
        category.save()
        return redirect('category-admin')
    category_form = CategoryForm(instance=category)
    return render(request,'edit_category.html',{"category": category_form, 'id': id})



@login_required(login_url='admin_login')
def delete_category(request,id):
    category=Category.objects.get(id=id)
    category.delete()
    return redirect('category-admin')



@login_required(login_url='admin_login')
def edit_dish(request, id):
    dish = Dish.objects.get(id=id)
    if request.method == 'POST':
        dish.name=request.POST['name']
        dish.price=request.POST['price']
        dish.description=request.POST['description']
        dish.imageUrl=request.POST['imageUrl']
        dish.is_gluten_free=True if request.POST.get('is_gluten_free') == 'on' else False
        dish.is_vegetarian=True if request.POST.get('is_vegetarian') == 'on' else False
        category_id = request.POST['categories']
        category = Category.objects.get(id=category_id)
        dish.category = category
        dish.save()
        return redirect('dishes-admin', id=category_id)

    categories = list(Category.objects.all()).copy()
    categories.remove(dish.category)
    categories.insert(0, dish.category)
    return render(request, 'edit_dish.html', {'dish_id': dish.id, 'categories': categories, 'dish': DishForm(instance=dish)})



@login_required(login_url='admin_login')
def delete_dish(request, id):
    dish = Dish.objects.get(id=id)
    category_id = dish.category.id
    dish.delete()
    return redirect('dishes-admin', id=category_id)



@login_required(login_url='admin_login')
def dishes_admin(request,id):
    category = Category.objects.get(id=id)
    dishes = Dish.objects.all()
    return render(request,'dishes_admin.html',{"id":category.id, "dishes":dishes})



@login_required(login_url='admin_login')
def add_category(request):
    if request.method=='POST':
        new_category=Category(
           name=request.POST['category_name'], 
           imageUrl=request.POST['imageUrl'] 
        )
        new_category.save()
        return redirect('category-admin')
    return render(request,'add_category.html')



@login_required(login_url='admin_login')
def add_dish(request):
    is_gluten_free = True if request.POST.get('is_gluten_free') == 'on' else False
    is_vegetarian = True if request.POST.get('is_vegetarian') == 'on' else False
    if request.method == 'POST':
        new_dish=Dish(
            name=request.POST['name'],
            price=request.POST['price'],
            description=request.POST['description'],
            imageUrl=request.POST['imageUrl'],
            is_gluten_free=is_gluten_free,
            is_vegetarian=is_vegetarian,
            category_id=request.POST['categories']
        )
        new_dish.save()
        return redirect('dishes-admin',id=request.POST['categories'])
    categories=Category.objects.all()
    return render(request, 'add_dish.html', {'categories': categories})


@login_required(login_url='signup_user')
def logout_user(request):
    logout(request)
    return redirect('signup_user')


@login_required(login_url='admin_login')
def logout_manager(request):
    logout(request)
    return redirect('admin_login')

users/templates/add_category.html
{%extends 'menu_manager.html'%}
{%block content%}


<div class="container">
    <h2 style="color: white; font-weight: bold;" >קטגוריה חדשה</h2>
    <form action="{% url 'add_category' %}" method="POST">
      {% csrf_token %} 
      <div class="form-group">
        <label for="category_name" style="color: white; font-weight: bold;">שם הקטגוריה:</label>
        <input type="text" class="form-control" id="category_name" name="category_name" value="{{ form.category_name.value }}" required>
      </div>
      <div class="form-group">
        <label for="imageUrl" style="color: white; font-weight: bold;">קישור לתמונה:</label>
        <input type="text" class="form-control" id="imageUrl" name="imageUrl" value="{{ form.imageUrl.value }}" required>
      </div>
      <button type="submit" class="btn btn-primary" style="color: white; font-weight: bold;">+</button>
    </form>
  </div>

{%endblock content%}

users/templates/add_dish.html
{%extends 'menu_manager.html'%}
{%block content%}

    <div class="container">
      <h2 style="color: white; font-weight: bold;" >הוספת מנה</h2>
      <form action="{% url 'add-dish' %}" method="POST" style="direction: rtl;">
        {%csrf_token%}
        <div class="form-group">
          <label for="name" style="color: white; font-weight: bold;">שם המנה:</label>
          <input type="text" class="form-control" id="name" name="name" value="{{ form.name.value }}" required>
        </div>
        <div class="form-group">
         <label for="price" style="color: white; font-weight: bold;">מחיר:</label>
         <div class="input-group">
             <input type="text" class="form-control" id="price" name="price" value="{{ form.price.value }}" required>
         </div>
     </div>     
        <div class="form-group">
          <label for="description" style="color: white; font-weight: bold;">תיאור המנה:</label>
          <input type="text" class="form-control" id="description" name="description" value="{{ form.description.value }}" required>
        </div>
        <div class="form-group">
         <label for="imageUrl" style="color: white; font-weight: bold;">קישור לתמונה:</label>
         <input type="text" class="form-control" id="imageUrl" name="imageUrl" value="{{ form.imageUrl.value }}" required>
       </div>
       <div>
         <select name="categories" >
             {% for category in categories %}
             <option value="{{category.id}}">{{category.name}}</option>
             {%endfor%}
         </select>
      </div>
        <div>
         <input type="checkbox" name="is_gluten_free" > ?מכיל גלוטן
      </div>
      <div>
         <input type="checkbox" name="is_vegetarian" > ?צמחוני
      </div>
        <button type="submit" class="btn btn-primary" style="color: white; font-weight: bold;">+</button>
    </div>
      </form>
    
    
{%endblock content%}

users/templates/admin_login.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>כניסת מנהל</title>
	<style>
		.container {
			display: flex;
			flex-direction: column;
			align-items: center;
			justify-content: center;
			height: 100vh;
		}
		body {
			display: flex;
			justify-content: center;
			align-items: center;
			height: 100vh;
			margin: 0;
		  }
		  
		  form {
			display: flex;
			flex-direction: column;
			align-items: center;
			padding: 20px;
			border: 1px solid black;
			border-radius: 5px;
			box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.5);
		  }
	  
		  input[type="text"], input[type="password"] {
			padding: 10px;
			margin-bottom: 10px;
			border-radius: 5px;
			border: 1px solid gray;
		  }
	  
		  input[type="submit"] {
			padding: 10px 20px;
			background-color: #4CAF50;
			color: white;
			border: none;
			border-radius: 5px;
			cursor: pointer;
			font-size: 16px;
			box-shadow: 0px 0px 5px rgba(0, 0, 0, 0.5);
		  }
	</style>
</head>
<body>
	<div class="container">
		<h1>כניסת מנהל</h1>
		<form action="{%url 'admin_login'%}" method="POST">
			{% csrf_token %}
			<label for="username">:שם משתמש</label>
			<input type="text" name="username" required>
            {% if error_message %}
                <p>{{ error_message }}</p>
            {% endif %}
			<label for="password">:סיסמא</label>
			<input type="password" name="password" required>
            {% if error_message %}
                <p>{{ error_message }}</p>
            {% endif %}
			<input type="submit" value="כניסה">
		</form>
	</div>
</body>
</html>

users/templates/category_admin.html
{%extends 'menu_manager.html'%}
{%block content%}
<form action="{%url 'category-admin'%}" style="direction: rtl;">
    {%csrf_token%}
    <div style="display: flex; flex-wrap: wrap; justify-content: center;">
    {% for category in categories %}
      <div class="card" style="width: 18rem; margin: 20px;">
          <img src="{{category.imageUrl}}" height="300px" class="card-img-top">
          <div class="card-body">
              <h5 class="card-title">{{category.name}}</h5>
              <div style="display: flex; flex-wrap: wrap; justify-content: center;">
                <a href="{%url 'dishes-admin' id=category.id%}" class="btn btn-secondary btn-lg" role="button">צפייה במנות</a>
                <div>
                  <a href="{% url 'edit_category' id=category.id %}"  class="btn btn-secondary btn-lg" role="button">עריכה</a>
                  <a href="{% url 'delete_category' id=category.id %}" class="btn btn-secondary btn-lg" role="button">מחיקה</a>
                </div>
              </div>
          </div>
      </div>
    {% endfor %}
    </div>
</form>
{%endblock content%}

users/templates/category_user.html
{% extends 'layout.html' %}
{% block content %}
<form action="{% url 'category_user'%}" style="direction: rtl;">
    {%csrf_token%}
    <div style="display: flex; flex-wrap: wrap; justify-content: center;">
      {% for category in categories %}
        <div class="card" style="width: 18rem; margin: 20px;">
            <img src="{{category.imageUrl}}" height="300px" class="card-img-top">
            <div class="card-body">
            <div style="display: flex; flex-wrap: wrap; justify-content: center;">
                <a href="{% url 'dishes_user' id=category.id %}"  class="btn btn-secondary btn-lg" role="button">{{category.name}}</a>
            </div>
            </div>
        </div>
      {% endfor %}
      
      
  </div>
  </form>
{% endblock content %}

users/templates/dishes_admin.html
{% extends 'menu_manager.html' %}
{% block content %}
<form action="{% url 'dishes-admin' id=id %}" style="direction: rtl;">
    {% csrf_token %}
    <div style="display: flex; flex-wrap: wrap; justify-content: center;">
      {% for dish in dishes %}
      {%if dish.category.id == id%}
        <div class="card" style="width: 18rem; margin: 20px;">
          <img src="{{ dish.imageUrl }}" height="300px" class="card-img-top" >
          <div class="card-body">
            {% if dish.is_vegetarian == True  %}
                <h5 class="card-title">{{ dish.name }} - {{ dish.price }}₪ (צמחוני)</h5>
            {% else %}
                <h5 class="card-title">{{ dish.name }} - {{ dish.price }}₪</h5>
            {% endif %}
            {% if dish.is_gluten_free == True %}
            <p style="font-family: 'Times New Roman', Times, serif; font-size: medium;">המנה מכילה גלוטן</p>
            {% else %}
                <p style="font-family: 'Times New Roman', Times, serif; font-size: medium;">המנה ללא גלוטן</p>
            {% endif %}
        
        
            <p class="card-text">{{ dish.description }}</p>
            <a href="{% url 'edit_dish' id=dish.id %}" class="btn btn-secondary btn-lg" role="button">עריכה</a>
            <a href="{% url 'delete_dish' id=dish.id %}" class="btn btn-danger btn-sm" role="button">מחיקה</a>
          </div>
        </div>
      {%endif%}
      {% endfor %}
    </div>
  </form>
{% endblock content %}

users/templates/dishes_user.html
{% extends 'layout.html' %}
{% block content %}
<form action="{% url 'dishes_user' id=category.id %}" style="direction: rtl;">
  {% csrf_token %}
  <div style="display: flex; flex-wrap: wrap; justify-content: center;">
    {% for dish in dishes %}
    {%if dish.category.id == category.id%}
      <div class="card" style="width: 18rem; margin: 20px;">
        <img src="{{ dish.imageUrl }}" height="300px" class="card-img-top" >
        <div class="card-body">
          {% if dish.is_vegetarian == True  %}
              <h5 class="card-title">{{ dish.name }} - {{ dish.price }}₪ (צמחוני)</h5>
          {% else %}
              <h5 class="card-title">{{ dish.name }} - {{ dish.price }}₪</h5>
          {% endif %}
          {% if dish.is_gluten_free == True %}
          <p style="font-family: 'Times New Roman', Times, serif; font-size: medium;">המנה מכילה גלוטן</p>
          {% else %}
              <p style="font-family: 'Times New Roman', Times, serif; font-size: medium;">המנה ללא גלוטן</p>
          {% endif %}
      
          <p class="card-text">{{ dish.description }}</p>
          <a href="{% url 'cart' id=dish.id%}" class="btn btn-secondary btn-lg" role="button">הוסף לעגלה</a>
        </div>
      </div>
    {%endif%}
    {% endfor %}
  </div>
</form>
{% endblock content %}

users/templates/edit_category.html
{%extends 'menu_manager.html'%}
{%block content%}

<div class="container">
    <h2 style="color: white; font-weight: bold;" >עריכת קטגוריה</h2>
    <form action="{% url 'edit_category' id=id %}" method="POST">
      {% csrf_token %}
      <div class="form-group">
        <label for="name" style="color: white; font-weight: bold;">שם הקטגוריה:</label>
        <input type="text" class="form-control" id="name" name="name" value="{{ category.name.value }}" required>
      </div>
      <div class="form-group">
        <label for="imageUrl" style="color: white; font-weight: bold;">קישור לתמונה:</label>
        <input type="text" class="form-control" id="imageUrl" name="imageUrl" value="{{ category.imageUrl.value }}" required>
      </div>

      <button type="submit" class="btn btn-primary" style="color: white; font-weight: bold;">עדכון עריכת קטגוריה</button>
    </form>
  </div>

</form>
{%endblock content%}

users/templates/edit_dish.html
{%extends 'menu_manager.html'%}
{%block content%}

    <div class="container">
      <h2 style="color: white; font-weight: bold;" >עריכת מנה</h2>
      <form action="{% url 'edit_dish' id=dish_id %}" method="POST">
        {% csrf_token %}
        <div class="form-group">
          <label for="name" style="color: white; font-weight: bold;">שם המנה:</label>
          <input type="text" class="form-control" id="name" name="name" value="{{ dish.name.value }}" required>
        </div>
        <div class="form-group">
         <label for="price" style="color: white; font-weight: bold;">מחיר:</label>
         <div class="input-group">
             <input type="text" class="form-control" id="price" name="price" value="{{ dish.price.value }}" required>
         </div>
     </div>     
        <div class="form-group">
          <label for="description" style="color: white; font-weight: bold;">תיאור המוצר:</label>
          <input type="text" class="form-control" id="description" name="description" value="{{ dish.description.value }}" ₪ required>
        </div>
        <div class="form-group">
         <label for="imageUrl" style="color: white; font-weight: bold;">קישור לתמונה:</label>
         <input type="text" class="form-control" id="imageUrl" name="imageUrl" value="{{ dish.imageUrl.value }}" required>
       </div>
        <div>
            {% if dish.is_gluten_free.value %}
         <input type="checkbox" name="is_gluten_free" checked > ?מכיל גלוטן
            {% else %}
            <input type="checkbox" name="is_gluten_free" > ?מכיל גלוטן
            {% endif %}
      </div>
      <div>
          {% if dish.is_vegetarian.value %}
         <input type="checkbox" name="is_vegetarian" checked> ?צמחוני
          {% else %}
            <input type="checkbox" name="is_vegetarian" > ?מכיל גלוטן
            {% endif %}
      </div>
       <div>
         <select name="categories" >
             {% for category in categories %}
             <option value="{{category.id}}">{{category.name}}</option>
             {%endfor%}
         </select>
      </div>
        <button type="submit" class="btn btn-primary" style="color: white; font-weight: bold;">עדכון עריכת מנה</button>
      </form>
    </div>
    
{%endblock content%}

users/templates/login.html
<!DOCTYPE html>
<html>
<head>
	<title>Login Page</title>
    <style>

		body {
		  display: flex;
		  justify-content: center;
		  align-items: center;
		  height: 100vh;
		  margin: 0;
		}
		
		form {
		  display: flex;
		  flex-direction: column;
		  align-items: center;
		  padding: 20px;
		  border: 1px solid black;
		  border-radius: 5px;
		  box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.5);
		}
	
		input[type="text"], input[type="password"] {
		  padding: 10px;
		  margin-bottom: 10px;
		  border-radius: 5px;
		  border: 1px solid gray;
		}
	
		input[type="submit"] {
		  padding: 10px 20px;
		  background-color: #4CAF50;
		  color: white;
		  border: none;
		  border-radius: 5px;
		  cursor: pointer;
		  font-size: 16px;
		  box-shadow: 0px 0px 5px rgba(0, 0, 0, 0.5);
		}
	  </style>
</head>
<body>
	<form action="{%url 'login_view'%}" method="POST">
        {% csrf_token %}
		<h2>כניסה</h2>
		<label for="username">:שם משתמש</label>
		<input type="text" id="username" name="username" required>
        {% if error_message %}
            <p>{{ error_message }}</p>
        {% endif %}
		<label for="password">:סיסמא</label>
		<input type="password" id="password" name="password" required>
        {% if error_message %}
            <p>{{ error_message }}</p>
        {% endif %}
		<input type="submit" value="כניסה">
	</form>
</body>
</html>

users/templates/signup_user.html
<!DOCTYPE html>
<html>
<head>
    <title>SignUp</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <style>
      
      .container {
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        height: 100vh;
      }
      body {
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100vh;
        margin: 0;
        }
        
        form {
        display: flex;
        flex-direction: column;
        align-items: center;
        padding: 20px;
        border: 1px solid black;
        border-radius: 5px;
        box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.5);
        }
      
        input[type="text"], input[type="password"] {
        padding: 10px;
        margin-bottom: 10px;
        border-radius: 5px;
        border: 1px solid gray;
        }
      
        input[type="submit"] {
        padding: 10px 20px;
        background-color: #4CAF50;
        color: white;
        border: none;
        border-radius: 5px;
        cursor: pointer;
        font-size: 16px;
        box-shadow: 0px 0px 5px rgba(0, 0, 0, 0.5);
        }
    </style>
</head>
<body>
<div class="container">
    <h1>הרשמה</h1>
    <form action="{%url 'signup_user'%}" method="POST">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_first_name">:שם פרטי</label>
            <input type="text" class="form-control" id="id_first_name" name="first_name" required>
        </div>
        <div class="form-group">
            <label for="id_last_name">:שם משפחה</label>
            <input type="text" class="form-control" id="id_last_name" name="last_name" required>
        </div>
        <div class="form-group">
            <label for="id_email">:אימייל</label>
            <input type="email" class="form-control" id="id_email" name="email" required>
        </div>
        <div class="form-group">
            <label for="id_username">:שם משתמש</label>
            <input type="text" class="form-control" id="id_username" name="username" required>
        </div>
        <div class="form-group">
            <label for="id_password">:סיסמא</label>
            <input type="password" class="form-control" id="id_password" name="password" required>
        </div>
        <button type="submit" class="btn btn-primary">הרשמה</button>
    </form>
</div>
</body>
</html>

users/templates/update_user.html
{%extends 'layout.html'%}
{%block content%}


<div class="container">
  <h2 style="color: white; font-weight: bold;" >עדכון פרטי משתמש</h2>
  <form action="{%url 'update_user'%}" method="POST">
    {% csrf_token %}
    <div class="form-group">
      <label for="id_first_name" style="color: white; font-weight: bold;">שם פרטי:</label>
      <input type="text" class="form-control" id="id_first_name" name="first_name" value="{{ form.first_name.value }}" required>
    </div>
    <div class="form-group">
      <label for="id_last_name" style="color: white; font-weight: bold;">שם משפחה:</label>
      <input type="text" class="form-control" id="id_last_name" name="last_name" value="{{ form.last_name.value }}" required>
    </div>
    <div class="form-group">
      <label for="id_email" style="color: white; font-weight: bold;">כתובת אימייל:</label>
      <input type="email" class="form-control" id="id_email" name="email" value="{{ form.email.value }}" required>
    </div>
    <div class="form-group">
      <label for="id_username" style="color: white; font-weight: bold;">שם משתמש:</label>
      <input type="text" class="form-control" id="id_username" name="username" value="{{ form.username.value }}" required>
    </div>
    <div class="form-group">
      <label for="id_password" style="color: white; font-weight: bold;">סיסמה:</label>
      <input type="password" class="form-control" id="id_password" name="password" required>
    </div>
    <button type="submit" class="btn btn-primary" style="color: white; font-weight: bold;">עדכן פרטי משתמש</button>
  </form>
</div>


{%endblock content%}